name: battery_buddy
description: A mobile inventory management app for batteries.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add Firebase dependencies
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  provider: ^6.0.0
  intl: ^0.18.0
  google_fonts: ^6.0.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # set to min_sdk_version of your Android project
  remove_alpha_ios: true

flutter:
  uses-material-design: true